"""add beta applications table

Revision ID: 75fa30b56ece
Revises: a1b2c3d4e5f6
Create Date: 2026-03-20 23:16:33.547823

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75fa30b56ece'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_applications',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('use_case', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='beta_application_pkey')
    )
    with op.batch_alter_table('beta_applications', schema=None) as batch_op:
        batch_op.create_index('beta_application_email_idx', ['email'], unique=False)
        batch_op.create_index('beta_application_status_idx', ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beta_applications', schema=None) as batch_op:
        batch_op.drop_index('beta_application_status_idx')
        batch_op.drop_index('beta_application_email_idx')

    op.drop_table('beta_applications')
    # ### end Alembic commands ###
