"""add custom_config to accounts

Revision ID: 391923893f21
Revises: 8d7e6c5b4a39
Create Date: 2026-04-18 21:02:35.696987

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '391923893f21'
down_revision = '8d7e6c5b4a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_config', models.types.LongText(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('custom_config')

    # ### end Alembic commands ###
