FROM langgenius/dify-api:1.12.0

USER root

WORKDIR /app/api

COPY --chown=dify:dify . /app/api/
COPY --chown=dify:dify --chmod=755 docker/entrypoint.sh /entrypoint.sh

RUN uv pip install --python /app/api/.venv/bin/python "curl_cffi==0.13.0"

USER dify
